### PR TITLE
WIP: Add seed to URL

### PR DESCRIPTION
**Pull request by TanviKumar**
The seed is not saved when user tries to save. Do make suggestions on implementation.

### CODE REVIEW

**Comment by stebanos** [comment]
@TanviKumar I think it's a nice start but it doesn't follow the query string syntax (for example -L4uLB99JzFHMPcVoiTm?seed=GKB instead of -L4uLB99JzFHMPcVoiTm/GKB). Also I haven't tested your code but I don't think it actually loads the right seed in this case? It's just about changing the URL?

**Comment by TanviKumar** [comment]
@stebanos Yes, I'm still trying to figure that out.

**Comment by TanviKumar** [comment]
@stebanos Works now!

**Comment by stebanos** [comment]
Thank you! Great job!

**Pull request merged**
