### PR TITLE
following the preamble syntax for import

### PR DESCRIPTION
**Pull request by kunal-mohta**
As mentioned in #5

### CODE REVIEW

**Comment by stebanos** [comment]
Looks good, but I would let the ```if (n.startsWith('import'))``` conditional go before ```else if (m)```.

**Comment by kunal-mohta** [comment]
I did that.
Can I know why you want it to be that way, though?

**Comment by stebanos** [comment]
Because the import error would not throw if m would be evaluate to true, and import should be seen as a reserved keyword.

**Comment by kunal-mohta** [comment]
Oh! Okay. I missed that.

**Pull request merged**
